#!/usr/bin/env python
import sys
import argparse

import bookmark

SUB_COMMANDS = ["add"]
def preprocess_cmd_line():
    mode = None
    args = list(enumerate(sys.argv[1:]))
    args.reverse()
    for i, arg in args:
        if arg in SUB_COMMANDS:
            mode = arg
            del sys.argv[i+1]
    return mode

mode = preprocess_cmd_line()
if mode is None and ("-h" not in sys.argv or "--help" not in sys.argv):
    print "No subcommand given, valid subcommands are %s" % ", ".join(SUB_COMMANDS)
argp = argparse.ArgumentParser()
argp.add_argument("-u", "--url", help="URL to bookmark")
args = argp.parse_args()

if mode == "add":
    print args.url
